# Generated by Django 2.2 on 2021-06-02 06:41

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(default=1, upload_to=accounts.models.upload_pic),
            preserve_default=False,
        ),
    ]
